### PR TITLE
Xenial py3 qt5

### PR DESCRIPTION
**Pull request by elpaso**

### CODE REVIEW

**Comment by Gustry** [comment]
Great !
Which version of GDAL is included now ? Before this PR, it was still 1.10 and I was thinking that we should update.

**Comment by elpaso** [comment]
@Gustry still testing ... please wait.
GDAL was the main reason to upgrade ... the other was Py3/Qt5

**Comment by elpaso** [comment]
@Gustry merged. Quick and dirty but working. I'd really appreciate some help in cleaning this thing up... The image has grown in size considerably, but I cannot remove much because we still need `git` and `build-essentials`: most of our plugins have complex build steps.

**Comment by Gustry** [comment]
Thanks for your work on Py3/QT5.
Unfortunately, all our builds were failing since yesterday afternoon.
I rolled back to elpasso/qgis-testing-environment until I find why, and now everything is working fine. No problem on your side ?

**Comment by elpaso** [comment]
No

**Comment by elpaso** [comment]
@Gustry well, you are right: there is an error in the setup script, I'll fix it

**Pull request closed without merging**
