### PR TITLE
fix small mistakes in the readme, add .gitignore

### PR DESCRIPTION
**Pull request by Gustry**
Just some small fixes.
Thanks for this project.

### CODE REVIEW

**Comment by elpaso** [comment]
Thanks you for the fixes!

**Comment by Gustry** [comment]
Any reason why this PR hasn't been merged ?

**Comment by elpaso** [comment]
No, my intention was to merge it, probably I pressed the wrong button... let me check

**Comment by elpaso** [comment]
Done now, sorry

**Comment by Gustry** [comment]
No problem, thanks

**Pull request merged**
